Repository RoyalHaskoningDHV/sam, pull requests merged in 2022-08, with the labels that each got.

#52 Fixed some documentation and updated links
  docs/source/data.rst
  docs/source/feature_engineering.rst
  docs/source/intro.rst
  docs/source/visualization.rst
  sam/visualization/plot_feature_importances.py
Labels: Priority: High, Type: Documentation

#54 Bugfix: publishing workflow for PyPI
  .github/workflows/python-publish.yml
  README.md
  pyproject.toml
  sam/__init__.py
Labels: Priority: High, Type: Bug

#61 Updated readme to contain an example
  README.md
Labels: Priority: Low, Type: Documentation
