Repository RoyalHaskoningDHV/sam, pull requests merged in 2022-07, with the labels that each got.

#2 fix readthedocs requirements
  .gitignore
  .readthedocs.yaml
  CHANGELOG.md
  docs/requirements.txt
Labels: Priority: Medium, Type: Bug, Type: Maintenance

#22 move to pyproject.toml
  .github/workflows/unittest.yml
  CHANGELOG.md
  MANIFEST.in
  pipelines/build-documentation.yml
  pipelines/build-package.yml
  pipelines/run-linting.yml
  pipelines/run-unittests.yml
  pyproject.toml
  setup.cfg
  setup.py
Labels: Priority: Low, Type: Maintenance

#24 Fixed version info for docs
  CHANGELOG.md
  docs/requirements.txt
  docs/source/conf.py
  pyproject.toml
Labels: Priority: Medium, Type: Bug

#23 Feature engineering and model refactoring
  .gitignore
  CHANGELOG.md
  conftest.py
  data/rainbow_beach.parquet
  docs/source/conf.py
  docs/source/feature_engineering.rst
  docs/source/minimumviableproject.rst
  docs/source/models.rst
  docs/source/samquantiledemo.rst
  examples/SamQuantileMLPdemo.ipynb
  examples/feature_engineering.ipynb
  examples/minimumviableproject.ipynb
  examples/mlp.ipynb
  pyproject.toml
  sam/feature_engineering/__init__.py
  sam/feature_engineering/base_feature_engineering.py
  sam/feature_engineering/simple_feature_engineering.py
  sam/feature_engineering/tests/test_base_feature_engineering.py
  sam/feature_engineering/tests/test_simple_feature_engineering.py
  sam/metrics/custom_callbacks.py
  sam/metrics/quantile_evaluation.py
  sam/models/TimeseriesMLP.py
  sam/models/__init__.py
  sam/models/base_model.py
  sam/models/benchmark.py
  sam/models/keras_templates.py
  sam/models/sam_shap_explainer.py
  sam/models/spc_model.py
  sam/models/tests/test_mlp.py
  sam/models/tests/test_sam_quantile_mlp.py
  sam/models/tests/test_spc_model.py
  sam/models/utils.py
  sam/preprocessing/differencing.py
  sam/visualization/performance_evaluation_fixed_predict_ahead.py
  sam/visualization/plot_feature_importances.py
  sam/visualization/quantile_plot.py
Labels: Priority: High, Type: Feature, Type: Improvement

#39 This should fix the RTD
  .readthedocs.yaml
  docs/requirements.txt
  docs/source/conf.py
  docs/source/exploration.rst
  docs/source/feature_engineering.rst
  pyproject.toml
Labels: Priority: High, Type: Documentation

#45 Renaming models
  CHANGELOG.md
  docs/source/models.rst
  examples/mlp.ipynb
  sam/metrics/custom_callbacks.py
  sam/metrics/quantile_evaluation.py
  sam/models/__init__.py
  sam/models/base_model.py
  sam/models/benchmark.py
  sam/models/linear_model.py
  sam/models/mlp_model.py
  sam/models/sam_shap_explainer.py
  sam/models/spc_model.py
  sam/models/tests/test_linear_model.py
  sam/models/tests/test_mlp_model.py
  sam/models/tests/test_spc_model.py
  sam/visualization/performance_evaluation_fixed_predict_ahead.py
  sam/visualization/plot_feature_importances.py
  sam/visualization/quantile_plot.py
Labels: Priority: Medium, Type: Improvement

#46 Some small updates to the docs
  docs/source/data.rst
  docs/source/examples.rst
  docs/source/index.rst
  docs/source/preprocessing.rst
  docs/source/projects/SamQuantileMLPdemo.html
  docs/source/projects/minimumviableproject.html
Labels: Priority: High, Type: Documentation
